name: Update WoW TOC Interface

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1"

permissions: {}

concurrency:
  group: wow-interface-updater
  cancel-in-progress: false

jobs:
  update:
    name: Update interface versions
    if: github.repository == 'Stanzilla/AdvancedInterfaceOptions'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push the update branch.
      pull-requests: write # Required to open or update the pull request.
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: toc
        uses: Nnoggie/wow-interface-updater@9566e33fd0abb13201221f8f35fd93e7beef0129 # v1.1.0
        with:
          toc-glob: AdvancedInterfaceOptions.toc

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: steps.toc.outputs.changed == 'true'
        with:
          branch: automation/wow-interface
          delete-branch: true
          add-paths: AdvancedInterfaceOptions.toc
          commit-message: "chore: update WoW interface versions"
          title: "chore: update WoW interface versions"
          body: ${{ steps.toc.outputs.pr-body }}
